### ISSUE TITLE
Kernel Panic boot on ThinkPad E15 Gen 2

### ISSUE THREAD

**Issue by Samaritan4186** [gorouflex/amdlaptophackintosh#1]
Please see the picture. It just immediately kernel panics.
![2023-07-01-01-51-58-399](https://github.com/gorouflex/amdlaptophackintosh/assets/86473412/8b3a61c9-b80b-43de-a6eb-c31558dce3cc)

**Comment by Samaritan4186** [comment]
[opencore-2023-07-01-103057.txt](https://github.com/gorouflex/amdlaptophackintosh/files/11925459/opencore-2023-07-01-103057.txt)
hoping a log helps

**Comment by gorouflex** [comment]
Did you change any OC Quirks from the original EFI?

**Comment by Samaritan4186** [comment]
Which ones in particular? I had to change a couple or it got stuck at exitBS start

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
Try to turn on SetupVirtualMap in booter quirks, and what version of macOS/EFI that you used to run it?

**Comment by gorouflex** [comment]
Also read my Caution note,it might solve the problem

**Comment by Samaritan4186** [comment]
I'm trying 13.4.1

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
Try to disable NRed first also try to enable DevirtualiseMmio

**Comment by Samaritan4186** [comment]
okay

**Comment by Samaritan4186** [comment]
just did those modifications and will try to boot now

**Comment by gorouflex** [comment]
https://github.com/gorouflex/amdlaptophackintosh/releases/tag/1.4
This is my current efi, consider to fix again , this kernel panic is about the kext

**Comment by Samaritan4186** [comment]
Thanks! Will try now!

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
just copied your new efi to the flash drive, hope this fixes it!

**Comment by gorouflex** [comment]
Ok if it still has Kernel Panic please consider to follow the guide about this error on the Internet

**Comment by Samaritan4186** [comment]
I have looked. I cannot find anything that explains it so I pray this helps!

**Comment by Samaritan4186** [comment]
also what do you mean by RDR images?

**Comment by Samaritan4186** [comment]
am attempting boot now

**Comment by Samaritan4186** [comment]
same kernel panic... no clue whats causing it at this point
I may try use your old efi or maybe even the sonoma efis?

**Comment by gorouflex** [comment]
Yeah you can try

**Comment by Samaritan4186** [comment]
trying to boot ventura with an old version of your sonoma efi
will let you know how it goes... and it just crashed at the same spot. I am going to start trying monterey to see if there is any deviation.

**Comment by gorouflex** [comment]
Also can you provide your laptop spec more clearly and detail???

**Comment by gorouflex** [comment]
Also you can try my friend’s EFI

**Comment by gorouflex** [comment]
https://github.com/nlqanh524/Hackintosh-Asus-TM420UA

**Comment by Samaritan4186** [comment]
https://www.bhphotovideo.com/c/product/1576152-REG/lenovo_20t80005us_ts_e15_g2_ryzen5_4500u_8gb_256gb_15_6_w10p.html best I can do without booting into my other os

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
> https://github.com/nlqanh524/Hackintosh-Asus-TM420UA

sure, will do!

**Comment by Samaritan4186** [comment]
copying it over now

**Comment by Samaritan4186** [comment]
yep same crash from his...

**Comment by gorouflex** [comment]
Strange…did you set your BIOS settings?

**Comment by Samaritan4186** [comment]
what bios settings should I use?

**Comment by Samaritan4186** [comment]
?

**Comment by gorouflex** [comment]
Svm mode should be off
Secure Boot off
Fast Boot off
Sara mode AHCI
Turn off Legacy mode
Some settings will not exist on your bios,you can skip it

**Comment by Samaritan4186** [comment]
all of those that exist in my bios I have turned off

**Comment by Samaritan4186** [comment]
I have no clue how to proceed

**Comment by gorouflex** [comment]
You may follow the guide in Dortania for AMD Desktop to build your own EFI,replace WhateverGreen kext to NootedRed

**Comment by Samaritan4186** [comment]
I have in fact tried this.
I cannot find any reason that this is failing
This is extremely odd, isn't it?

**Comment by gorouflex** [comment]
This may your laptop is anti-hackintosh or something…sorry because I couldn’t fix this error 😭

**Comment by Samaritan4186** [comment]
don't worry. I am going to try one last thing with safe mode and if that doesn't work I am going to wait for a reply from another person with an r5 4500u efi

WAIT:

right before I kernel panic I get Fault CR2... yada yada. That talks about cpu.

Could this be in any way related to the kernel patches?

**Comment by gorouflex** [comment]
Idk…may try to patch new version

**Comment by Samaritan4186** [comment]
what do you mean by this?

**Comment by Samaritan4186** [comment]
what efi of yours are you using at this current moment? the latest?
1.4?

**Comment by gorouflex** [comment]
Yes, I mean maybe you have to patch the newer version than my patch

**Comment by Samaritan4186** [comment]
A newer version? Where?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
https://github.com/AMD-OSX/AMD_Vanilla/blob/master/patches.plist

**Comment by Samaritan4186** [comment]
I've tried applying these

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
Might you need to meet an AMD Hackintosh expert for this problem…

**Comment by Samaritan4186** [comment]
There's no official support for laptops so they likely wouldn't help.

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
Yeah because AMD laptop hackintosh it’s still a mystery journey to get in…specially APU and other things

**Comment by Samaritan4186** [comment]
Hopefully some day someone makes an efi for my system... It's not the end of the world though since I have a surface and other hackintoshes

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
found an option that may be of help in my bios. Wish me luck

**Comment by Samaritan4186** [comment]
Nevermind, no luck unfortunately

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
YO DUDE I GOT FURTHER

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
![2023-07-02-14-00-18-559.jpg](https://github.com/gorouflex/amdlaptophackintosh/assets/86473412/69dfaf5c-19f6-4903-bb31-ade5ebd12c47)

**Comment by gorouflex** [comment]
? Is still a kernel panic

**Comment by Samaritan4186** [comment]
Still kernel panicking but I got further this time

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
is there another place we may speak? github issues are getting a bit annoying lol

**Comment by Samaritan4186** [comment]
So far I finally have it kernel panicking to there, where can I proceed from here?

**Comment by Samaritan4186** [comment]
Update! I no longer kernel panic I just hang at appleps2controller newcommandbyte47 so gonna disable the voodoo PS2 kexts!

**Comment by Samaritan4186** [comment]
Update 2: it's just edit after edit but I'm getting close to a working system!

**Comment by Samaritan4186** [comment]
Update: we are up and running!![PXL_20230702_175512325.jpg](https://github.com/gorouflex/amdlaptophackintosh/assets/86473412/f935a201-3a12-4d11-a3c3-f6e157435801)

**Comment by gorouflex** [comment]
oh??

**Comment by gorouflex** [comment]
what EFI you're using??

**Comment by gorouflex** [comment]
hey and if you want íncrease your VRAM please take a look of my GUIDE in github @Samaritan4186

**Comment by gorouflex** [comment]
@Samaritan4186 https://github.com/gorouflex/amdlaptophackintosh/blob/main/installation-guide.md

**Comment by Samaritan4186** [comment]
> hey and if you want íncrease your VRAM please take a look of my GUIDE in github @Samaritan4186 

My bios already had an option

**Comment by gorouflex** [comment]
oh ok :D can you also share your EFI?

**Comment by Samaritan4186** [comment]
Will do asap

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
Just curious: what's the best smbios for these hackintoshes? I've seen some use imacpro1,1 aswell as MacPro7,1 and also MacBookPro16,3.

Also does iMessage work for you?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Samaritan4186** [comment]
> Just curious: what's the best smbios for these hackintoshes? I've seen some use imacpro1,1 aswell as MacPro7,1 and also MacBookPro16,3.
> 
> Also does iMessage work for you?
> 


Just thought to ask

**Comment by gorouflex** [comment]
Yes iMess works for me but I cannot sync to iCloud

**Comment by Samaritan4186** [comment]
What smbios do you use personally?

Inviato da Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by gorouflex** [comment]
Just use recommended SmBios from NRed repo

**Comment by gorouflex** [comment]
MacBookPro16,3

**Comment by Samaritan4186** [comment]
> Update: we are up and running!![PXL_20230702_175512325.jpg](https://user-images.githubusercontent.com/86473412/250388595-f935a201-3a12-4d11-a3c3-f6e157435801.jpg)

also cpu is misreporting (this image is even outdated because now its reporting as a core i5!)

**Comment by gorouflex** [comment]
try to rename from NVRAM of my EFI

**Comment by gorouflex** [comment]
![Screen Shot 2023-07-04 at 09 50 01](https://github.com/gorouflex/amdlaptophackintosh/assets/98001973/505588a3-4747-4edb-90f5-8a58a1f8ef93)

**Comment by gorouflex** [comment]
also you can set your **ProcessorType** to 0 or 1537

**Comment by gorouflex** [comment]
also you can contact me through Discord
Username: gorouflex

**Comment by gorouflex** [comment]
Also added Fix CPU name in installation guide, take a look!
https://github.com/gorouflex/amdlaptophackintosh/blob/main/installation-guide.md
